export type Language = "en" | "es";

export const translations = {
  en: {
    // App Title
    app: {
      title: "eTicketing",
      subtitle: "Smart Logistics Management",
      company: "eTicketing",
    },
    // Login Page
    login: {
      title: "eTicketing",
      subtitle: "Smart Logistics Management",
      driver: "Driver",
      driverDesc: "Log in or sign up to create tickets",
      continueAsDriver: "Continue as Driver",
      attendant: "Destination Attendant",
      attendantDesc: "Scan QR codes and confirm deliveries",
      continueAsAttendant: "Continue as Attendant",
      overview: "Overview",
      overviewDesc: "View all tickets and drivers",
      continueAsOverview: "View Overview",
      driverLogin: "Driver Login",
      enterEmailToLogin: "Enter your email to log in or sign up",
      emailAddress: "Email Address",
      loginId: "Login ID",
      loggingIn: "Logging in...",
      logInSignUp: "Log In / Sign Up",
      noAccountWarning:
        "If you don't have an account, one will be created for you.",
      back: "← Back",
      truckIT: "eTicketing",
      digitalTicketingSystem: "Digital Ticketing System",
      copyright: "© 2025 eTicketing. All rights reserved.",
      fullName: "Full Name",
      johnDoe: "John Doe",
      creatingAccount: "Creating Account...",
      createAccount: "Create Account",
      yourUniqueDriverQRCode:
        "Your unique driver QR code will be generated automatically.",
    },
    // Home Page
    home: {
      scanQR: "Scan QR Code",
      scanQRDesc: "Scan truck or ticket QR code",
      openScanner: "Open Scanner",
      enterTicketID: "Enter Ticket ID",
      enterTicketIDDesc: "Type ticket ID (e.g., TKT-12345) to access a ticket",
      search: "Search",
      createTicket: "Create Ticket",
      createTicketDesc: "Manually create new ticket",
      createNewTicket: "Create New Ticket +",
      shiftStatus: "Shift Status",
      startShift: "Start my shift",
      endShift: "End my shift",
      recentActivity: "Recent Activity",
      noRecentActivity: "No recent activity",
      createTicketOrScan:
        "Create a new ticket or scan a QR code to get started",
      scanDriverQR: "Scan a driver QR code to view their tickets",
      tons: "tons",
      driverDashboard: "Driver Dashboard",
      driverInfo: "Driver Info",
      todayTickets: "Today's Tickets",
      noTicketsCreatedYet: "No tickets created yet",
      active: "Active",
      verified: "Verified",
      delivered: "Delivered",
      closed: "Closed",
      endShiftWarning:
        "You have active tickets. Complete them before ending your shift.",
      completeActiveTickets: "Complete Active Tickets",
      endShiftConfirm: "End my shift",
      cancel: "Cancel",
    },
    // Driver Profile
    driverProfile: {
      title: "Driver Profile",
      myProfile: "My Profile",
      myQRCode: "My QR Code",
      myTruckAndCarrier: "My Truck & Carrier",
      selectCarrier: "Select Carrier*",
      selectTruck: "Select Truck *",
      pickupLocation: "Pickup Location*",
      chooseCarrier: "Choose a carrier",
      chooseTruck: "Choose a truck",
      choosePickupLocation: "Choose pickup location",
      downloadQRCode: "Download QR Code",
      activeTickets: "Active Tickets",
      noActiveTickets: "No active tickets",
      createNewTicket: "Create a new ticket to get started",
      status: "Status",
      finishTheShift: "Finish the Shift",
      startTheShift: "Start the Shift",
      loadingProfile: "Loading profile...",
      home: "Home",
      logout: "Logout",
      selectPickupLocation: "Select Pickup Location",
      saveChanges: "Save Changes",
      selectTruckRequired: "Please select a truck",
      profileUpdated: "Profile updated successfully",
      errorUpdating: "Error updating profile",
    },
    // Ticket Details
    ticketDetails: {
      title: "Ticket Details",
      ticketURL: "Ticket URL",
      copy: "Copy",
      copied: "Copied!",
      status: "Status",
      truck: "Truck",
      carrier: "Carrier",
      driver: "Driver",
      product: "Product",
      origin: "Origin",
      destination: "Destination",
      grossWeight: "Gross Weight",
      tareWeight: "Tare Weight",
      netWeight: "Net Weight",
      tons: "tons",
      forDestinationAttendant: "For Destination Attendant",
      confirmerName: "Confirmer Name",
      signature: "Signature",
      confirm: "Confirm",
      signOff: "Sign Off",
      ticketSignedOff: "Ticket Signed Off",
      successfullySignedOff: "You have successfully signed off the ticket",
      ticketHasBeenConfirmed: "Ticket has been confirmed",
    },
    // Destination Attendant Confirmation
    destinationConfirm: {
      confirmDelivery: "Confirm Delivery",
      ticketID: "Ticket ID",
      confirmerName: "Attendant Name",
      driverName: "Driver Name",
      enterYourFullName: "Enter your full name",
      deliveryLocation: "Delivery Location",
      yourSignature: "Your Signature",
      signToConfirmDelivery: "Sign to confirm delivery",
      confirmationSummary: "Confirmation Summary",
      reviewBeforeSubmitting: "Review before submitting",
      confirmed: "Confirmed",
      notEntered: "Not entered",
      notSigned: "Not signed",
      signed: "✓ Signed",
      pickupLocation: "Pickup Location",
      locationConfirmed: "✓ Location confirmed",
      deliveryConfirmed: "Delivery Confirmed!",
      ticketHasBeenSuccessfullyConfirmed:
        "The ticket has been successfully confirmed and closed.",
      ticketDetails: "Ticket Details",
      ticketImage: "Ticket Image",
      noTicketImageYet: "There is no ticket image yet",
      confirmationDetails: "Confirmation Details",
      confirmedBy: "Confirmed By",
      status: "Status",
      deliveryDetails: "Delivery Details",
      viewTicket: "View Ticket",
      goToDashboard: "Go to Dashboard",
      cancel: "Cancel",
      confirmingDots: "Confirming...",
      ticketNotFound: "Ticket Not Found",
      theTicketYoureLookingForDoesntExist:
        "The ticket you're looking for doesn't exist.",
      goBack: "Go Back",
      loadingTicket: "Loading ticket...",
      missingInformation: "Missing Information",
      pleaseFillInAllRequiredFields: "Please fill in all required fields",
      ticketConfirmed: "Ticket Confirmed",
      ticketHasBeenSuccessfullyConfirmedAndClosed:
        "Ticket has been successfully confirmed",
      errorConfirmingTicket: "Error confirming ticket",
      failedToConfirmTicket: "Failed to confirm ticket",
      failedToLoadTicket: "Failed to load ticket",
      truck: "Truck",
      netWeight: "Net Weight",
      tons: "tons",
    },
    // Overview
    overview: {
      title: "Overview",
      subtitle: "All tickets and drivers",
      allTicketsAndDrivers: "All tickets and drivers",
      tickets: "Tickets",
      drivers: "Drivers",
      searchByTicketTruckCarrier: "Search by ticket ID, truck, or carrier...",
      searchTickets: "Search tickets...",
      searchDrivers: "Search drivers...",
      advancedFilters: "Advanced Filters",
      allStatuses: "All Statuses",
      allCarriers: "All Carriers",
      allStatus: "All Status",
      active: "Active",
      inactive: "Inactive",
      noTicketsFound: "No tickets found",
      noDriversFound: "No drivers found",
      today: "Today",
      allDates: "All Dates",
      date: "Date",
      status: "Status",
      closedTicketsToday: "Closed Tickets Today",
      trucks: "Trucks",
      searchTrucks: "Search trucks...",
      noTrucksFound: "No trucks found",
      loadingMore: "Loading more...",
      loadMoreTrucks: "Load More Trucks",
      id: "ID",
    },
    // Create Ticket
    createTicket: {
      title: "Create Ticket",
      subtitle: "Scale verification",
      carrier: "Carrier",
      truckID: "Truck ID",
      driver: "Driver",
      notAssigned: "Not assigned",
      selectCarrier: "Select Carrier",
      selectTruck: "Select Truck",
      selectPickupLocation: "Select Pickup Location",
      pickupLocation: "Pickup Location *",
      destinationSite: "Destination Site *",
      enterDestination: "Enter Destination",
      netWeight: "Net Weight *",
      enterNetWeight: "Enter Net Weight",
      productName: "Product Name (Optional)",
      enterProductName: "Enter Product Name (Optional)",
      signature: "Signature",
      signatureRequired: "Signature required",
      creatingTicket: "Creating...",
      activateTicket: "Activate",
      completeActiveTicketFirst: "Complete Active Ticket First",
      ticketCreated: "Ticket Created",
      ticketCreatedSuccessfully: "Ticket has been created successfully",
      errorCreatingTicket: "Error creating ticket",
      failedToCreateTicket: "Failed to create ticket",
      driverInactiveWarning:
        "Driver status is inactive. Please start the shift at driver profile page.",
      driverInactiveWarningFull:
        "Driver status is inactive. Please start the shift at driver dashboard page to create tickets.",
      completeShiftSetup:
        "Please complete your shift setup (carrier, truck, and pickup location) to create tickets.",
      activeTicketWarning:
        "You have an active ticket. Complete it before creating a new one.",
      saveAsDraft: "Save",
    },
    // Scale House
    scaleHouse: {
      title: "Scale House Verification",
      ticketStatus: "Ticket Status",
      verifiedAtScale: "Verified at Scale",
      ticketID: "Ticket ID",
      carrier: "Carrier",
      truck: "Truck",
      product: "Product",
      grossWeight: "Gross Weight",
      tareWeight: "Tare Weight",
      netWeight: "Net Weight",
      tons: "tons",
      downloadQR: "Download QR",
      continue: "Continue",
      downloadingQR: "Downloading...",
    },
    // Driver Sign Up
    driverSignUp: {
      title: "Driver Sign Up",
      subtitle: "Create your driver account",
      fullName: "Full Name",
      email: "Email",
      selectCarrier: "Select Carrier",
      selectTruck: "Select Truck",
      signUp: "Sign Up",
      signingUp: "Signing Up...",
      accountCreated: "Account Created",
      accountCreatedSuccessfully: "Your account has been created successfully",
      errorCreatingAccount: "Error creating account",
      failedToCreateAccount: "Failed to create account",
      nameRequired: "Name is required",
      emailRequired: "Email is required",
      carrierRequired: "Please select a carrier",
      truckRequired: "Please select a truck",
    },
    // Driver Dashboard
    driverDashboard: {
      title: "Driver Dashboard",
      activeTickets: "Active Tickets",
      noActiveTickets: "No active tickets",
      recentTickets: "Recent Tickets",
      noRecentTickets: "No recent tickets",
      startShift: "Start my shift",
      endShift: "End my shift",
      shiftStatus: "Shift Status",
      active: "Active",
      inactive: "Inactive",
    },
    // Driver Info
    driverInfo: {
      title: "Driver Information",
      name: "Name",
      email: "Email",
      carrier: "Carrier",
      truck: "Truck",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
    },
    // Deliver Ticket
    deliverTicket: {
      title: "Deliver Ticket",
      ticketDetails: "Ticket Details",
      signature: "Signature",
      signatureRequired: "Signature required",
      confirmerName: "Confirmer's Name",
      enterNameOfPersonConfirmingDelivery:
        "Enter name of person confirming delivery",
      confirmDelivery: "Confirm Delivery",
      confirming: "Confirming...",
      cancel: "Cancel",
      deliveryConfirmed: "Delivery Confirmed",
      deliveryConfirmedSuccessfully: "Delivery has been confirmed successfully",
      errorConfirmingDelivery: "Error confirming delivery",
      failedToConfirmDelivery: "Failed to confirm delivery",
      deliveryConfirmation: "Delivery Confirmation",
      deliveryLocation: "Delivery Location",
    },
    // Destination Attendant
    destinationAttendant: {
      title: "Destination Attendant",
      confirmDelivery: "Confirm Delivery",
      yourName: "Your Name",
      enterYourName: "Enter your name",
      signature: "Signature",
      signToConfirmDelivery: "Sign to confirm delivery",
      confirm: "Confirm",
      confirming: "Confirming...",
      cancel: "Cancel",
      deliveryConfirmed: "Delivery Confirmed",
      deliveryConfirmedSuccessfully: "Delivery has been confirmed successfully",
      errorConfirmingDelivery: "Error confirming delivery",
      failedToConfirmDelivery: "Failed to confirm delivery",
      deliveryConfirmation: "Delivery Confirmation",
    },
    // Admin
    admin: {
      title: "Admin Dashboard",
      totalTickets: "total tickets",
      exportCSV: "Export CSV",
      searchTickets: "Search tickets...",
      filterByStatus: "Filter by Status",
      allStatus: "All Status",
      created: "Created",
      verified: "Verified",
      delivered: "Delivered",
      closed: "Closed",
      noTicketsFound: "No tickets found",
      ticketID: "Ticket ID",
      carrier: "Carrier",
      truck: "Truck",
      product: "Product",
      status: "Status",
      createdAt: "Created At",
    },
    // Index / Home Dashboard
    index: {
      scanQRCode: "Scan QR Code",
      scanDriverQRCode: "Scan driver QR code to view their tickets",
      enterTicketID: "Enter Ticket ID",
      typeTicketID: "Type ticket ID (e.g., TKT-12345) to access a ticket",
      search: "Search",
      createTicket: "Create Ticket",
      manuallyCreateNewTicket: "Manually create new ticket",
      createNewTicket: "Create New Ticket +",
      shiftStatus: "Shift Status",
      startShift: "Start my shift",
      endShift: "End my shift",
      recentActivity: "Recent Activity",
      noRecentActivity: "No recent activity",
      createTicketOrScan:
        "Create a new ticket or scan a QR code to get started",
      scanTruckOrTicket: "Scan truck or ticket QR code",
      openScanner: "Open Scanner",
      scanDriverQRCodeToViewTickets:
        "Scan a driver QR code to view their tickets",
    },
    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      driver: "Driver",
      close: "Close",
      logout: "Logout",
      confirmLogout: "Confirm Logout",
      areYouSureLogout: "Are you sure you want to log out?",
      settings: "Settings",
      language: "Language",
      selectLanguage: "Select Language",
      choosePreferredLanguage: "Choose your preferred language",
      english: "English",
      spanish: "Español",
      home: "Home",
      profile: "Profile",
      back: "Back",
      next: "Next",
      previous: "Previous",
      submit: "Submit",
      confirm: "Confirm",
      warning: "Warning",
      info: "Information",
      noData: "No data available",
      loading_: "Loading",
      tryAgain: "Try Again",
      refresh: "Refresh",
      lightMode: "Light mode",
      darkMode: "Dark mode",
      login: "Login",
      signUp: "Sign Up",
      user: "User",
      chooseYourRole: "Choose your role",
      continueAsRole: "Continue as",
      name: "Name",
      email: "Email",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      createdAt: "Created At",
      updatedAt: "Updated At",
      actions: "Actions",
      view: "View",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      export: "Export",
      import: "Import",
      download: "Download",
      upload: "Upload",
      copy: "Copy",
      copied: "Copied!",
      share: "Share",
      print: "Print",
      help: "Help",
      about: "About",
      contact: "Contact",
      privacy: "Privacy",
      terms: "Terms",
      yes: "Yes",
      no: "No",
      ok: "OK",
      done: "Done",
      finish: "Finish",
      start: "Start",
      end: "End",
      begin: "Begin",
      continue: "Continue",
      skip: "Skip",
      goBack: "Go Back",
      goHome: "Go Home",
      goToDashboard: "Go to Dashboard",
      viewDetails: "View Details",
      moreInfo: "More Info",
      lessInfo: "Less Info",
      showMore: "Show More",
      showLess: "Show Less",
      seeAll: "See All",
      selectAll: "Select All",
      deselectAll: "Deselect All",
      clearAll: "Clear All",
      resetFilters: "Reset Filters",
      applyFilters: "Apply Filters",
      noResults: "No results found",
      noResultsFound: "No results found",
      tryDifferentSearch: "Try a different search",
      somethingWentWrong: "Something went wrong",
      pleaseRefresh: "Please refresh the page",
      errorOccurred: "An error occurred",
      tryAgainLater: "Please try again later",
      unauthorized: "Unauthorized",
      forbidden: "Forbidden",
      notFound: "Not Found",
      serverError: "Server Error",
      networkError: "Network Error",
      connectionError: "Connection Error",
      timeoutError: "Request Timeout",
      validationError: "Validation Error",
      requiredField: "This field is required",
      invalidEmail: "Invalid email address",
      invalidPhoneNumber: "Invalid phone number",
      passwordTooShort: "Password is too short",
      passwordsDoNotMatch: "Passwords do not match",
      confirmPassword: "Confirm Password",
      newPassword: "New Password",
      oldPassword: "Old Password",
      changePassword: "Change Password",
      resetPassword: "Reset Password",
      forgotPassword: "Forgot Password",
      rememberMe: "Remember Me",
      stayLoggedIn: "Stay Logged In",
      loginSuccessful: "Login Successful",
      logoutSuccessful: "Logout Successful",
      sessionExpired: "Session Expired",
      pleaseLoginAgain: "Please login again",
      tryAdjustingFilters: "Try adjusting your filters",
      createFirstTicket: "Create your first ticket to get started",
      pleaseWait: "Please wait while we fetch the ticket details",
      carrier: "Carrier",
      truck: "Truck",
    },
  },
  es: {
    // App Title
    app: {
      title: "eTicketing",
      subtitle: "Gestión Inteligente de Logística",
      company: "eTicketing",
    },
    // Login Page
    login: {
      title: "eTicketing",
      subtitle: "Gestión Inteligente de Logística",
      driver: "Conductor",
      driverDesc: "Inicia sesión o regístrate para crear boletos",
      continueAsDriver: "Continuar como Conductor",
      attendant: "Asistente de Destino",
      attendantDesc: "Escanea códigos QR y confirma entregas",
      continueAsAttendant: "Continuar como Asistente",
      overview: "Resumen",
      overviewDesc: "Ver todos los boletos y conductores",
      continueAsOverview: "Ver Resumen",
      driverLogin: "Inicio de Sesión del Conductor",
      enterEmailToLogin:
        "Ingresa tu correo electrónico para iniciar sesión o registrarte",
      emailAddress: "Dirección de Correo Electrónico",
      loginId: "ID de inicio de sesión",
      loggingIn: "Iniciando sesión...",
      logInSignUp: "Iniciar Sesión / Registrarse",
      noAccountWarning: "Si no tienes una cuenta, se creará una para ti.",
      back: "← Atrás",
      truckIT: "eTicketing",
      digitalTicketingSystem: "Sistema de Boletos Digital",
      copyright: "© 2025 eTicketing. Todos los derechos reservados.",
      fullName: "Nombre Completo",
      johnDoe: "Juan Pérez",
      creatingAccount: "Creando Cuenta...",
      createAccount: "Crear Cuenta",
      yourUniqueDriverQRCode:
        "Tu código QR de conductor único se generará automáticamente.",
    },
    // Home Page
    home: {
      scanQR: "Escanear Código QR",
      scanQRDesc: "Escanea el código QR del camión o boleto",
      openScanner: "Abrir Escáner",
      enterTicketID: "Ingresa ID del Boleto",
      enterTicketIDDesc:
        "Escribe el ID del boleto (p. ej., TKT-12345) para acceder a un boleto",
      search: "Buscar",
      createTicket: "Crear Boleto",
      createTicketDesc: "Crear manualmente un nuevo boleto",
      createNewTicket: "Crear Nuevo Boleto +",
      shiftStatus: "Estado del Turno",
      startShift: "Iniciar Turno",
      endShift: "Finalizar Turno",
      recentActivity: "Actividad Reciente",
      noRecentActivity: "Sin actividad reciente",
      createTicketOrScan:
        "Crea un nuevo boleto o escanea un código QR para comenzar",
      scanDriverQR: "Escanea el código QR del conductor para ver sus boletos",
      tons: "toneladas",
      driverDashboard: "Panel del Conductor",
      driverInfo: "Información del Conductor",
      todayTickets: "Boletos de Hoy",
      noTicketsCreatedYet: "Sin boletos creados aún",
      active: "Activo",
      verified: "Verificado",
      delivered: "Entregado",
      closed: "Cerrado",
      endShiftWarning:
        "Tienes boletos activos. Complétalos antes de finalizar tu turno.",
      completeActiveTickets: "Completar Boletos Activos",
      endShiftConfirm: "Finalizar Turno",
      cancel: "Cancelar",
    },
    // Driver Profile
    driverProfile: {
      title: "Perfil del Conductor",
      myProfile: "Mi Perfil",
      myQRCode: "Mi Código QR",
      myTruckAndCarrier: "Mi Camión y Transportista",
      selectCarrier: "Seleccionar Transportista*",
      selectTruck: "Seleccionar Camión *",
      pickupLocation: "Ubicación de Recogida*",
      chooseCarrier: "Elige una transportista",
      chooseTruck: "Elige un camión",
      choosePickupLocation: "Elige ubicación de recogida",
      downloadQRCode: "Descargar Código QR",
      activeTickets: "Boletos Activos",
      noActiveTickets: "Sin boletos activos",
      createNewTicket: "Crea un nuevo boleto para comenzar",
      status: "Estado",
      finishTheShift: "Finalizar el Turno",
      startTheShift: "Iniciar el Turno",
      loadingProfile: "Cargando perfil...",
      home: "Inicio",
      logout: "Cerrar Sesión",
      selectPickupLocation: "Seleccionar Ubicación de Recogida",
      saveChanges: "Guardar Cambios",
      selectTruckRequired: "Por favor selecciona un camión",
      profileUpdated: "Perfil actualizado exitosamente",
      errorUpdating: "Error al actualizar el perfil",
    },
    // Ticket Details
    ticketDetails: {
      title: "Detalles del Boleto",
      ticketURL: "URL del Boleto",
      copy: "Copiar",
      copied: "¡Copiado!",
      status: "Estado",
      truck: "Camión",
      carrier: "Transportista",
      driver: "Conductor",
      product: "Producto",
      origin: "Origen",
      destination: "Destino",
      grossWeight: "Peso Bruto",
      tareWeight: "Peso Tara",
      netWeight: "Peso Neto",
      tons: "toneladas",
      forDestinationAttendant: "Para Asistente de Destino",
      confirmerName: "Nombre del Confirmador",
      signature: "Firma",
      confirm: "Confirmar",
      signOff: "Firmar",
      ticketSignedOff: "Boleto Firmado",
      successfullySignedOff: "Has firmado exitosamente el boleto",
      ticketHasBeenConfirmed: "El boleto ha sido confirmado",
    },
    // Destination Attendant Confirmation
    destinationConfirm: {
      confirmDelivery: "Confirmar Entrega",
      ticketID: "ID del Boleto",
      confirmerName: "Nombre del Confirmador",
      driverName: "Nombre del Conductor",
      enterYourFullName: "Ingresa tu nombre completo",
      deliveryLocation: "Ubicación de Entrega",
      yourSignature: "Tu Firma",
      signToConfirmDelivery: "Firma para confirmar la entrega",
      confirmationSummary: "Resumen de Confirmación",
      reviewBeforeSubmitting: "Revisa antes de enviar",
      confirmed: "Confirmado",
      notEntered: "No ingresado",
      notSigned: "No firmado",
      signed: "✓ Firmado",
      pickupLocation: "Ubicación de Recogida",
      locationConfirmed: "✓ Ubicación confirmada",
      deliveryConfirmed: "¡Entrega Confirmada!",
      ticketHasBeenSuccessfullyConfirmed:
        "El boleto ha sido confirmado y cerrado exitosamente.",
      ticketDetails: "Detalles del Boleto",
      ticketImage: "Imagen del Boleto",
      noTicketImageYet: "Aún no hay imagen del boleto",
      confirmationDetails: "Detalles de Confirmación",
      confirmedBy: "Confirmado Por",
      status: "Estado",
      deliveryDetails: "Detalles de Entrega",
      viewTicket: "Ver Boleto",
      goToDashboard: "Ir al Panel",
      cancel: "Cancelar",
      confirmingDots: "Confirmando...",
      ticketNotFound: "Boleto No Encontrado",
      theTicketYoureLookingForDoesntExist: "El boleto que buscas no existe.",
      goBack: "Volver",
      loadingTicket: "Cargando boleto...",
      missingInformation: "Información Faltante",
      pleaseFillInAllRequiredFields:
        "Por favor completa todos los campos requeridos",
      ticketConfirmed: "Boleto Confirmado",
      ticketHasBeenSuccessfullyConfirmedAndClosed:
        "El boleto ha sido confirmado exitosamente",
      errorConfirmingTicket: "Error al confirmar el boleto",
      failedToConfirmTicket: "Error al confirmar el boleto",
      failedToLoadTicket: "Error al cargar el boleto",
      truck: "Camión",
      netWeight: "Peso Neto",
      tons: "toneladas",
    },
    // Overview
    overview: {
      title: "Descripción General",
      subtitle: "Todos los boletos y conductores",
      allTicketsAndDrivers: "Todos los boletos y conductores",
      tickets: "Boletos",
      drivers: "Conductores",
      searchByTicketTruckCarrier:
        "Buscar por ID de boleto, camión o transportista...",
      searchTickets: "Buscar boletos...",
      searchDrivers: "Buscar conductores...",
      advancedFilters: "Filtros Avanzados",
      allStatuses: "Todos los Estados",
      allCarriers: "Todos los Transportistas",
      allStatus: "Todos los Estados",
      active: "Activo",
      inactive: "Inactivo",
      noTicketsFound: "No se encontraron boletos",
      noDriversFound: "No se encontraron conductores",
      today: "Hoy",
      allDates: "Todas las Fechas",
      date: "Fecha",
      status: "Estado",
      closedTicketsToday: "Boletos Cerrados Hoy",
      trucks: "Camiones",
      searchTrucks: "Buscar camiones...",
      noTrucksFound: "No se encontraron camiones",
      loadingMore: "Cargando más...",
      loadMoreTrucks: "Cargar Más Camiones",
      id: "ID",
    },
    // Create Ticket
    createTicket: {
      title: "Crear Boleto",
      subtitle: "Verificación de escala",
      carrier: "Transportista",
      truckID: "ID del Camión",
      driver: "Conductor",
      notAssigned: "No asignado",
      selectCarrier: "Seleccionar Transportista",
      selectTruck: "Seleccionar Camión",
      selectPickupLocation: "Seleccionar Ubicación de Recogida",
      pickupLocation: "Ubicación de Recogida *",
      destinationSite: "Sitio de Destino *",
      enterDestination: "Ingresa Destino",
      netWeight: "Peso Neto *",
      enterNetWeight: "Ingresa Peso Neto",
      productName: "Nombre del Producto (Opcional)",
      enterProductName: "Ingresa Nombre del Producto (Opcional)",
      signature: "Firma",
      signatureRequired: "Se requiere firma",
      creatingTicket: "Creando...",
      activateTicket: "Activar",
      completeActiveTicketFirst: "Completa Primero el Boleto Activo",
      ticketCreated: "Boleto Creado",
      ticketCreatedSuccessfully: "El boleto ha sido creado exitosamente",
      errorCreatingTicket: "Error al crear el boleto",
      failedToCreateTicket: "Error al crear el boleto",
      driverInactiveWarning:
        "Tu estado de conductor es inactivo. Por favor inicia tu turno en tu página de perfil.",
      driverInactiveWarningFull:
        "Tu estado de conductor es inactivo. Por favor inicia tu turno en tu página de panel para crear boletos.",
      completeShiftSetup:
        "Por favor completa tu configuración de turno (transportista, camión y ubicación de recogida) para crear boletos.",
      activeTicketWarning:
        "Tienes un boleto activo. Complétalo antes de crear uno nuevo.",
      saveAsDraft: "Guardar",
    },
    // Scale House
    scaleHouse: {
      title: "Verificación de Escala",
      ticketStatus: "Estado del Boleto",
      verifiedAtScale: "Verificado en Escala",
      ticketID: "ID del Boleto",
      carrier: "Transportista",
      truck: "Camión",
      product: "Producto",
      grossWeight: "Peso Bruto",
      tareWeight: "Peso Tara",
      netWeight: "Peso Neto",
      tons: "toneladas",
      downloadQR: "Descargar QR",
      continue: "Continuar",
      downloadingQR: "Descargando...",
    },
    // Driver Sign Up
    driverSignUp: {
      title: "Registro de Conductor",
      subtitle: "Crea tu cuenta de conductor",
      fullName: "Nombre Completo*",
      email: "Dirección de Correo Electrónico*",
      selectCarrier: "Transportista*",
      selectTruck: "Camión Predeterminado*",
      signUp: "Crear Cuenta",
      signingUp: "Creando Cuenta...",
      accountCreated: "Cuenta Creada",
      accountCreatedSuccessfully: "Tu cuenta ha sido creada exitosamente",
      errorCreatingAccount: "Error al crear la cuenta",
      failedToCreateAccount: "Error al crear la cuenta",
      nameRequired: "El nombre es requerido",
      emailRequired: "El correo electrónico es requerido",
      carrierRequired: "Por favor selecciona una transportista",
      truckRequired: "Por favor selecciona un camión",
      selectACarrier: "Selecciona una transportista",
      selectATruck: "Selecciona un camión",
      johnDoe: "Juan Pérez",
      driverAtExample: "conductor@ejemplo.com",
      uniqueQRCodeGenerated:
        "Tu código QR único de conductor se generará automáticamente.",
    },
    // Driver Dashboard
    driverDashboard: {
      title: "Panel del Conductor",
      activeTickets: "Boletos Activos",
      noActiveTickets: "Sin boletos activos",
      recentTickets: "Boletos Recientes",
      noRecentTickets: "Sin boletos recientes",
      startShift: "Iniciar Turno",
      endShift: "Finalizar Turno",
      shiftStatus: "Estado del Turno",
      active: "Activo",
      inactive: "Inactivo",
    },
    // Driver Info
    driverInfo: {
      title: "Información del Conductor",
      name: "Nombre",
      email: "Correo Electrónico",
      carrier: "Transportista",
      truck: "Camión",
      status: "Estado",
      active: "Activo",
      inactive: "Inactivo",
      driverInformation: "Información del Conductor",
      back: "Atrás",
      home: "Inicio",
      logout: "Cerrar Sesión",
    },
    // Deliver Ticket
    deliverTicket: {
      title: "Entregar Boleto",
      ticketDetails: "Detalles del Boleto",
      signature: "Firma",
      signatureRequired: "Se requiere firma",
      confirmerName: "Nombre del Confirmador",
      enterNameOfPersonConfirmingDelivery:
        "Ingresa el nombre de la persona que confirma la entrega",
      confirmDelivery: "Confirmar Entrega",
      confirming: "Confirmando...",
      cancel: "Cancelar",
      deliveryConfirmed: "Entrega Confirmada",
      deliveryConfirmedSuccessfully:
        "La entrega ha sido confirmada exitosamente",
      errorConfirmingDelivery: "Error al confirmar la entrega",
      failedToConfirmDelivery: "Error al confirmar la entrega",
      deliveryConfirmation: "Confirmación de Entrega",
      deliveryLocation: "Ubicación de Entrega",
    },
    // Destination Attendant
    destinationAttendant: {
      title: "Asistente de Destino",
      confirmDelivery: "Confirmar Entrega",
      yourName: "Tu Nombre",
      enterYourName: "Ingresa tu nombre",
      signature: "Firma",
      signToConfirmDelivery: "Firma para confirmar la entrega",
      confirm: "Confirmar",
      confirming: "Confirmando...",
      cancel: "Cancelar",
      deliveryConfirmed: "Entrega Confirmada",
      deliveryConfirmedSuccessfully:
        "La entrega ha sido confirmada exitosamente",
      errorConfirmingDelivery: "Error al confirmar la entrega",
      failedToConfirmDelivery: "Error al confirmar la entrega",
      deliveryConfirmation: "Confirmación de Entrega",
    },
    // Admin
    admin: {
      title: "Panel de Administración",
      totalTickets: "boletos totales",
      exportCSV: "Exportar CSV",
      searchTickets: "Buscar boletos...",
      filterByStatus: "Filtrar por Estado",
      allStatus: "Todos los Estados",
      created: "Creado",
      verified: "Verificado",
      delivered: "Entregado",
      closed: "Cerrado",
      noTicketsFound: "No se encontraron boletos",
      ticketID: "ID del Boleto",
      carrier: "Transportista",
      truck: "Camión",
      product: "Producto",
      status: "Estado",
      createdAt: "Creado En",
    },
    // Index / Home Dashboard
    index: {
      scanQRCode: "Escanear Código QR",
      scanDriverQRCode:
        "Escanea el código QR del conductor para ver sus boletos",
      enterTicketID: "Ingresa ID del Boleto",
      typeTicketID:
        "Escribe el ID del boleto (p. ej., TKT-12345) para acceder a un boleto",
      search: "Buscar",
      createTicket: "Crear Boleto",
      manuallyCreateNewTicket: "Crear manualmente un nuevo boleto",
      createNewTicket: "Crear Nuevo Boleto +",
      shiftStatus: "Estado del Turno",
      startShift: "Iniciar Turno",
      endShift: "Finalizar Turno",
      recentActivity: "Actividad Reciente",
      noRecentActivity: "Sin actividad reciente",
      createTicketOrScan:
        "Crea un nuevo boleto o escanea un código QR para comenzar",
      scanTruckOrTicket: "Escanea el código QR del camión o boleto",
      openScanner: "Abrir Escáner",
      scanDriverQRCodeToViewTickets:
        "Escanea el código QR del conductor para ver sus boletos",
    },
    // Not Found
    notFound: {
      pageNotFound: "Página No Encontrada",
      sorryPageDoesntExist: "Lo sentimos, la página que buscas no existe.",
      goHome: "Ir a Inicio",
      goBack: "Volver",
    },
    // Start Shift
    startShift: {
      title: "Iniciar Turno",
      selectCarrier: "Seleccionar Transportista",
      selectTruck: "Seleccionar Camión",
      selectPickupLocation: "Seleccionar Ubicación de Recogida",
      startShift: "Iniciar Turno",
      startingShift: "Iniciando turno...",
      shiftStarted: "Turno Iniciado",
      shiftStartedSuccessfully: "Tu turno ha sido iniciado exitosamente",
      errorStartingShift: "Error al iniciar el turno",
      failedToStartShift: "Error al iniciar el turno",
    },
    // Common
    common: {
      loading: "Cargando...",
      error: "Error",
      success: "Éxito",
      cancel: "Cancelar",
      save: "Guardar",
      delete: "Eliminar",
      edit: "Editar",
      close: "Cerrar",
      logout: "Cerrar Sesión",
      confirmLogout: "Confirmar Cierre de Sesión",
      areYouSureLogout: "¿Estás seguro de que deseas cerrar sesión?",
      settings: "Configuración",
      language: "Idioma",
      selectLanguage: "Seleccionar Idioma",
      choosePreferredLanguage: "Elige tu idioma preferido",
      english: "English",
      spanish: "Español",
      home: "Inicio",
      profile: "Perfil",
      back: "Atrás",
      next: "Siguiente",
      previous: "Anterior",
      submit: "Enviar",
      confirm: "Confirmar",
      warning: "Advertencia",
      info: "Información",
      noData: "Sin datos disponibles",
      loading_: "Cargando",
      tryAgain: "Intentar de Nuevo",
      refresh: "Actualizar",
      lightMode: "Modo Claro",
      darkMode: "Modo Oscuro",
      login: "Iniciar Sesión",
      signUp: "Registrarse",
      user: "Usuario",
      chooseYourRole: "Elige tu rol",
      continueAsRole: "Continuar como",
      name: "Nombre",
      email: "Correo Electrónico",
      status: "Estado",
      active: "Activo",
      inactive: "Inactivo",
      createdAt: "Creado En",
      updatedAt: "Actualizado En",
      actions: "Acciones",
      view: "Ver",
      search: "Buscar",
      filter: "Filtrar",
      sort: "Ordenar",
      export: "Exportar",
      import: "Importar",
      download: "Descargar",
      upload: "Cargar",
      copy: "Copiar",
      copied: "¡Copiado!",
      share: "Compartir",
      print: "Imprimir",
      help: "Ayuda",
      about: "Acerca de",
      contact: "Contacto",
      privacy: "Privacidad",
      terms: "Términos",
      yes: "Sí",
      no: "No",
      ok: "OK",
      done: "Hecho",
      finish: "Finalizar",
      start: "Iniciar",
      end: "Finalizar",
      begin: "Comenzar",
      continue: "Continuar",
      skip: "Saltar",
      goBack: "Volver",
      goHome: "Ir a Inicio",
      goToDashboard: "Ir al Panel",
      viewDetails: "Ver Detalles",
      moreInfo: "Más Información",
      lessInfo: "Menos Información",
      showMore: "Mostrar Más",
      showLess: "Mostrar Menos",
      seeAll: "Ver Todo",
      selectAll: "Seleccionar Todo",
      deselectAll: "Deseleccionar Todo",
      clearAll: "Limpiar Todo",
      resetFilters: "Restablecer Filtros",
      applyFilters: "Aplicar Filtros",
      noResults: "Sin resultados",
      noResultsFound: "No se encontraron resultados",
      tryDifferentSearch: "Intenta una búsqueda diferente",
      somethingWentWrong: "Algo salió mal",
      pleaseRefresh: "Por favor actualiza la página",
      errorOccurred: "Ocurrió un error",
      tryAgainLater: "Por favor intenta más tarde",
      unauthorized: "No Autorizado",
      forbidden: "Prohibido",
      notFound: "No Encontrado",
      serverError: "Error del Servidor",
      networkError: "Error de Red",
      connectionError: "Error de Conexión",
      timeoutError: "Tiempo de Espera Agotado",
      validationError: "Error de Validación",
      requiredField: "Este campo es requerido",
      invalidEmail: "Dirección de correo electrónico inválida",
      invalidPhoneNumber: "Número de teléfono inválido",
      passwordTooShort: "La contraseña es demasiado corta",
      passwordsDoNotMatch: "Las contraseñas no coinciden",
      confirmPassword: "Confirmar Contraseña",
      newPassword: "Nueva Contraseña",
      oldPassword: "Contraseña Anterior",
      changePassword: "Cambiar Contraseña",
      resetPassword: "Restablecer Contraseña",
      forgotPassword: "¿Olvidaste tu Contraseña?",
      rememberMe: "Recuérdame",
      stayLoggedIn: "Mantenerme Conectado",
      loginSuccessful: "Inicio de Sesión Exitoso",
      logoutSuccessful: "Cierre de Sesión Exitoso",
      sessionExpired: "Sesión Expirada",
      pleaseLoginAgain: "Por favor inicia sesión de nuevo",
      tryAdjustingFilters: "Intenta ajustar tus filtros",
      createFirstTicket: "Crea tu primer boleto para comenzar",
      pleaseWait: "Por favor espera mientras obtenemos los detalles del boleto",
      carrier: "Transportista",
      truck: "Camión",
    },
  },
};

export const getTranslation = (language: Language, path: string): string => {
  const keys = path.split(".");
  let value: any = translations[language];

  for (const key of keys) {
    if (value && typeof value === "object" && key in value) {
      value = value[key];
    } else {
      return path; // Return the path if translation not found
    }
  }

  return typeof value === "string" ? value : path;
};
